### ISSUE TITLE
XtextGrammarQuickfixProvider.workbench is not @Nullable

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1132]
```
1) null returned by binding at org.eclipse.xtext.ui.shared.SharedStateModule.configureIWorkbench(SharedStateModule.java:140)
 but org.eclipse.xtext.xtext.ui.editor.quickfix.XtextGrammarQuickfixProvider.workbench is not @Nullable
  while locating org.eclipse.ui.IWorkbench
    for field at org.eclipse.xtext.xtext.ui.editor.quickfix.XtextGrammarQuickfixProvider.workbench(Unknown Source)
  while locating org.eclipse.xtext.xtext.ui.editor.quickfix.XtextGrammarQuickfixProvider
  while locating org.eclipse.xtext.ui.editor.quickfix.IssueResolutionProvider
    for field at org.eclipse.xtext.ui.editor.validation.MarkerCreator.resolutionProvider(Unknown Source)
  while locating org.eclipse.xtext.ui.editor.validation.MarkerCreator
    for field at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.markerCreator(Unknown Source)
  while locating org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension
  while locating org.eclipse.xtext.ui.validation.IResourceUIValidatorExtension
```

**Comment by kthoms** [comment]
fixed in 2.19
