### ISSUE TITLE
XtextBuild crashes in JDT on "latest" locally

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1187]
```
java.lang.ArrayIndexOutOfBoundsException: 273
	at org.eclipse.jdt.internal.core.util.MementoTokenizer.nextToken(MementoTokenizer.java:57)
	at org.eclipse.jdt.internal.core.JavaProject.getHandleFromMemento(JavaProject.java:2008)
	at org.eclipse.jdt.internal.core.JavaElement.getHandleFromMemento(JavaElement.java:348)
	at org.eclipse.jdt.internal.core.JavaModel.getHandleFromMemento(JavaModel.java:159)
	at org.eclipse.jdt.internal.core.JavaElement.getHandleFromMemento(JavaElement.java:348)
	at org.eclipse.jdt.core.JavaCore.create(JavaCore.java:3504)
	at org.eclipse.jdt.core.JavaCore.create(JavaCore.java:3479)
	at org.eclipse.xtext.ui.containers.JavaProjectsStateHelper.initContainedURIs(JavaProjectsStateHelper.java:79)
	at org.eclipse.xtext.ui.containers.JavaProjectsState.doInitContainedURIs(JavaProjectsState.java:32)
	at org.eclipse.xtext.ui.containers.AbstractAllContainersState.initContainedURIs(AbstractAllContainersState.java:150)
	at org.eclipse.xtext.ui.containers.AbstractAllContainersState.isEmpty(AbstractAllContainersState.java:146)
	at org.eclipse.xtext.resource.containers.ContainerState.isEmpty(ContainerState.java:35)
	at org.eclipse.xtext.resource.containers.StateBasedContainer.isEmpty(StateBasedContainer.java:74)
	at org.eclipse.xtext.resource.containers.StateBasedContainerManager.getVisibleContainers(StateBasedContainerManager.java:99)
	at org.eclipse.xtext.resource.containers.StateBasedContainerManager.getVisibleContainers(StateBasedContainerManager.java:66)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescriptionManager.isAffected(DefaultResourceDescriptionManager.java:138)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.queueAffectedResources(ClusteringBuilderState.java:518)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:299)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:152)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:427)
	at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndBuild(XtextBuilder.java:361)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:468)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:240)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by cdietrich** [comment]
here is one bad memento

```
[=, o, r, g, ., x, t, e, x, t, ., e, x, a, m, p, l, e, ., m, y, d, s, l, 2, /, \, /, h, o, m, e, \, /, d, i, e, t, r, i, c, h, \, /, ., g, r, a, d, l, e, \, /, c, a, c, h, e, s, \, /, m, o, d, u, l, e, s, -, 2, \, /, f, i, l, e, s, -, 2, ., 1, \, /, o, r, g, ., e, c, l, i, p, s, e, ., x, t, e, x, t, \, /, o, r, g, ., e, c, l, i, p, s, e, ., x, t, e, x, t, ., x, t, e, x, t, ., g, e, n, e, r, a, t, o, r, \, /, 2, ., 2, 0, ., 0, -, S, N, A, P, S, H, O, T, \, /, d, 1, 3, f, 2, 1, d, 1, 9, 5, a, 5, 3, 8, d, 5, 5, 7, 5, 9, b, 1, f, c, 6, f, 9, c, 7, f, e, 9, c, 2, 8, 8, f, 5, 0, b, \, /, o, r, g, ., e, c, l, i, p, s, e, ., x, t, e, x, t, ., x, t, e, x, t, ., g, e, n, e, r, a, t, o, r, -, 2, ., 2, 0, ., 0, -, S, N, A, P, S, H, O, T, ., j, a, r, =, /, g, r, a, d, l, e, _, u, s, e, d, _, b, y, _, s, c, o, p, e, =, /]
```

have no clue what happens

**Comment by cdietrich** [comment]
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=551356
am not sure if the is a jdt or a buildship problem
cc @donat

**Comment by cdietrich** [comment]
issue is fixed again with the latest jdt nightly
