### ISSUE TITLE
Activation of shared.ui may happen too late

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#12]
We should make sure we activate shared.ui in a way that it is activated before any JDT/Resource events are flying around. 

I have seens this beeing a problem in my customers rcp and here it seems to be the same problem: https://www.eclipse.org/forums/index.php/t/1079073/

**Comment by spoenemann** [comment]
Could you describe here a bit more what the actual problem is?

**Comment by cdietrich** [comment]
if that would be that easy i would have it in the description. it basically ends in a state where projects are not proper built and the user has to do a manual clean. or the project is built twice. or not at all.

Following Actions may lead to such problems

* importing multiple projects at once
* opening multiple projects at once
* having xtext java projects that make heavy use of external jars and source links

**Comment by LorenzoBettini** [comment]
This looks like something similar I still experience (or at least I was experiencing that a few months ago, I haven't tried that lately). This happens in DSLs where I also provide an Import example wizard similar to those provided by Xtext. I think it could be reproduced also with a project wizard for your DSL (better if Xbase-based) that uses a source folder for generated files (but the wizard does not create that source folder)

Scenario 1: Start with a brand new workspace

- import or create the project through the wizard
- the source folder for generated files is not populated, not even created, and the project does not build due to a missing folder
- do a manual clean and everything works.

Scenario 2: Start with a brand new workspace

- create any Java project or plug-in project
- import or create the project through the wizard
- everything works and the source folder for the generated files is created and populated.

Scenario 3: Start with a workspace where a Java or plug-in project has been created in the past, but the workspace can be empty.

- import or create the project through the wizard
- everything works and the source folder for the generated files is created and populated.

I think this is somehow related to what @cdietrich describes?

**Comment by cdietrich** [comment]
i will try if we can create from the tons of issues we had arround this some reproducable test cases, unfortunately most of the problems are "sporadic"

**Comment by holzem** [comment]
I am not sure whether my problem 

> java.lang.ClassNotFoundException: org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory

is entirely related to this problem, but I found that the plug-in `org.eclipse.xtext.ui.shared` needs the plug-in `org.eclipse.xtext.ui` without it already loaded. The root cause seems to be that in the `org.eclipse.xtext.ui.shared` plug-in the dependency to `org.eclipse.xtext.ui` is marked as optional like some of the other dependencies

- `org.eclipse.xtext.ui`
- `org.eclipse.xtext.builder`
- `org.eclipse.jdt.core`
- `org.eclipse.jdt.ui`
- `org.eclipse.xtext.common.types.ui`
- `org.eclipse.ui.ide`

Making the dependencies required would solve the problem that the plug-ins are not activated in the expected order.

Since `org.eclipse.xtext.ui.shared.internal.ExecutableExtensionFactory` extends `AbstractGuiceAwareExecutableExtensionFactory` I find especially the optional dependency to `org.eclipse.xtext.ui` a bit funny. I found more than one error in the runtime depending on this connection between those plug-ins.

I made all dependencies `required` and after `eclipse.exe -clean` my problems vanished.

I am not sure wheter the dependencies in the xtext plug-ins would have sufficed. But the optional link between `org.eclipse.xtext.ui.shared` and `org.eclipse.xtext.ui` seems to be wrong, doesn't it?

Markus

**Comment by kthoms** [comment]
The dependencies on the JDT plugins in `org.eclipse.xtext.ui.shared` *must be optional*, since there are languages without any JDT dependencies. This is especially the case in environments where installations of JDT in the target IDE is a no go. Some workbenches that are mainly targeting embedded devices (where C/C++ is primary language) have this requirement.

I am not sure about the dependency to `org.eclipse.xtext.ui`; I'd also think that this is a mandatory dependency. We need to think about this dependency and the consequences it would have to make it mandatory.

**Comment by ymortier** [comment]
Hi,

Do you have plans to address this issue?

I develop an Eclipse RCP app. We updated from Eclipse 2012-12 to Eclipse 2020-09, from XText 2.20 to XText 2.23 and from Java 8 to Java 14. When I start the application from Eclipse I encounter the following issue:

```
java.lang.NoClassDefFoundError: org/eclipse/xtext/service/AbstractGenericModule
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:294)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:718)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:641)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:609)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:589)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:568)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:473)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at xxxx.MyDslActivator.getSharedStateModule(MyDslActivator.java:108)
        ...
Caused by: java.lang.ClassNotFoundException: org.eclipse.xtext.service.AbstractGenericModule cannot be found by org.eclipse.xtext.ui.shared_2.23.0.v20200831-0808
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 75 more
```

If I put the dependency from `org.eclipse.xtext.ui.shared` to `org.eclipse.xtext.ui` required then the problem vanishes. 

The problem is not reproducible with the application built by tycho. So maybe the problem comes from tests plugins?

**Comment by kthoms** [comment]
When this is happening for you when starting a runtime Eclipse only, then please try to define the launch order of the bundles in your launch configuration (Plug-ins tab) and make sure JDT is loaded at a lower start level. Would this work for you?

There are no concrete plans to address this, as there is no clear reproducible path nor solution path. If you can provide an example that would make it reproducible in a fresh Xtext installation, then we could have a look. Could you provide one?

**Comment by ymortier** [comment]
Thanks for your answer.

I have set all jdt plugins to start level 3 (default is 4) and I encounter the same issue.

I guess my problem is similar to the one reveal by https://github.com/eclipse/xtext-eclipse/issues/12#issuecomment-407026877

Unfortunately I can't provide an example. I forget to precise the target platform contains many other components (Sirius, Nebula, SWTBot/Spy for example). In development environment we mostly use SDK features of those components. Whereas the product only references needed features and we let tycho decides which dependencies to install. So there are differences between developement target platform and production one. Maybe I can disable all plugins and do trials/errors to find the configuration which cause the issue.

**Comment by ymortier** [comment]
I have selected a minimal set of plugins in the launch configuration: it works well!

I think the problem occurs because of a test or sample plugin. I let you know the specific configuration which causes the issue if I find it.
