### ISSUE TITLE
Domainmodel Example: NPE when executing 'Uncapitalize name' Quickfix

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#1220]
Given is the following `dmodel` file:
```
entity A {
	A : String

	b : String[]
	op foo() : String {
		return a
	}
}
```
When executing the `Uncapitalize name` on the property `A`, the following NPE is thrown:

```
327291 [main] ERROR org.eclipse.xtext.util.ExceptionAcceptor  - 
java.lang.NullPointerException
	at org.eclipse.xtext.formatting2.regionaccess.internal.AbstractTextSegment.contains(AbstractTextSegment.java:47)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.addReplacer(FormattableDocument.java:66)
	at org.eclipse.xtext.xbase.formatting2.XbaseFormatter._format(XbaseFormatter.java:222)
	at org.eclipse.xtext.example.domainmodel.formatting2.DomainmodelFormatter.format(DomainmodelFormatter.java:242)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:188)
	at org.eclipse.xtext.example.domainmodel.formatting2.DomainmodelFormatter._format(DomainmodelFormatter.java:149)
	at org.eclipse.xtext.example.domainmodel.formatting2.DomainmodelFormatter.format(DomainmodelFormatter.java:260)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:188)
	at org.eclipse.xtext.example.domainmodel.formatting2.DomainmodelFormatter._format(DomainmodelFormatter.java:135)
	at org.eclipse.xtext.example.domainmodel.formatting2.DomainmodelFormatter.format(DomainmodelFormatter.java:251)
	at org.eclipse.xtext.example.domainmodel.formatting2.DomainmodelFormatter._format(DomainmodelFormatter.java:81)
	at org.eclipse.xtext.example.domainmodel.formatting2.DomainmodelFormatter.format(DomainmodelFormatter.java:314)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:188)
	at org.eclipse.xtext.formatting2.AbstractFormatter2._format(AbstractFormatter2.java:208)
	at org.eclipse.xtext.example.domainmodel.formatting2.DomainmodelFormatter.format(DomainmodelFormatter.java:215)
	at org.eclipse.xtext.formatting2.AbstractFormatter2.format(AbstractFormatter2.java:276)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:151)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:180)
	at org.eclipse.xtext.serializer.impl.Serializer.serializeReplacement(Serializer.java:211)
	at org.eclipse.xtext.ui.editor.model.edit.DefaultTextEditComposer.getObjectEdits(DefaultTextEditComposer.java:176)
	at org.eclipse.xtext.ui.editor.model.edit.DefaultTextEditComposer.getTextEdit(DefaultTextEditComposer.java:146)
	at org.eclipse.xtext.ui.editor.model.edit.DefaultTextEditComposer.endRecording(DefaultTextEditComposer.java:129)
	at org.eclipse.xtext.ui.editor.model.edit.ReconcilingUnitOfWork.exec(ReconcilingUnitOfWork.java:57)
	at org.eclipse.xtext.ui.editor.model.edit.ReconcilingUnitOfWork.exec(ReconcilingUnitOfWork.java:1)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:431)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:164)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.modify(XtextDocument.java:157)
	at org.eclipse.xtext.ui.editor.model.edit.SemanticModificationWrapper.apply(SemanticModificationWrapper.java:32)
	at org.eclipse.xtext.ui.editor.quickfix.IssueResolution.apply(IssueResolution.java:76)
	at org.eclipse.xtext.ui.editor.quickfix.QuickAssistCompletionProposal.apply(QuickAssistCompletionProposal.java:36)
	at org.eclipse.xtext.ui.editor.hover.AnnotationWithQuickFixesHover$AnnotationInformationControl.apply(AnnotationWithQuickFixesHover.java:536)
	at org.eclipse.xtext.ui.editor.hover.AnnotationWithQuickFixesHover$AnnotationInformationControl.access$2(AnnotationWithQuickFixesHover.java:513)
	at org.eclipse.xtext.ui.editor.hover.AnnotationWithQuickFixesHover$AnnotationInformationControl$5.widgetSelected(AnnotationWithQuickFixesHover.java:507)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1098)
	at org.eclipse.swt.widgets.Link.wmNotifyChild(Link.java:696)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5787)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1988)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5353)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4817)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4820)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Link.callWindowProc(Link.java:160)
	at org.eclipse.swt.widgets.Widget.wmLButtonUp(Widget.java:1946)
	at org.eclipse.swt.widgets.Control.WM_LBUTTONUP(Control.java:5166)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4798)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4812)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3583)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
```
![screencast](https://user-images.githubusercontent.com/20393472/66834490-0288e100-ef5e-11e9-88be-af72cd755131.gif)

**Comment by cdietrich** [comment]
have no idea why the region is null here. also why the array is serialized here

**Comment by cdietrich** [comment]
Fixed

**Comment by miklossy** [comment]
Thanks for the fix, @cdietrich . Now there is no excpetion thrown any more, but a little bit weird behaviour is that an additional new line is inserted between the two properties after applying the quickfix. Could you please analyse that also? Thanks!

**Comment by cdietrich** [comment]
that is a different issue !!!!

**Comment by miklossy** [comment]
You are right, I will open an new issue for that!
