### ISSUE TITLE
XtextReconciler vs. IDocumentListener that calls readonly vs. folding

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1355]
given the Xtext Grammar

```
PackageDecl:
    'package' name=QualifiedName ';'
    (definitions+=Definition)*;


QualifiedName:
    ID ('.' ID)*;

Definition:
    ClassType;

ClassType:
    'class' name=ID
    '{'
    (parts+=MethodDecl)*
    '}';


MethodDecl:
    name=ID ('(' ')')
    (block=StatementBlock);

StatementBlock:
    {StatementBlock} '{'
    statements+=Statement*
    '}';

Statement:
    SwitchStatement;

SwitchStatement returns Statement:
    {SwitchStatement} 'switch' '(' value=ID ')' '{'
    '}';

```

and example model

```
package pkg;
class A {

  calc() {
    switch (a) {
    } // put your cursor after curly brace and press "return"
  } 
}
```

and having a `IDocumentListener` that calls readOnly

e.g. patched `org.eclipse.xtext.ui.editor.model.XtextDocument.addXtextDocumentContentObserver(IXtextDocumentContentObserver)` 

then editing the sample model as given in the comment gives

sometimes a wired formatting of the comment

**Comment by cdietrich** [comment]
the problem does not happen all the time. did not find out yet what needs to happen for it to be a problem.

**Comment by cdietrich** [comment]
<img width="549" alt="Bildschirmfoto 2020-02-24 um 15 44 05" src="https://user-images.githubusercontent.com/238736/75161692-84fb8b80-571c-11ea-9557-08de9f9f2012.png">

screenshot of wired folding

**Comment by cdietrich** [comment]
in the good case the folding is called like this

```
at org.eclipse.xtext.ui.editor.folding.DefaultFoldingStructureProvider.modelChanged(DefaultFoldingStructureProvider.java:103)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.notifyModelListeners(XtextDocument.java:219)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.lambda$1(XtextDocument.java:572)
	at org.eclipse.xtext.util.concurrent.IReadAccess.lambda$tryReadOnly$0(IReadAccess.java:56)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:524)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:496)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:135)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:52)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.lambda$0(XtextDocument.java:571)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3537)
	
```

in the bad case from the listener

```
at org.eclipse.xtext.ui.editor.folding.DefaultFoldingStructureProvider.modelChanged(DefaultFoldingStructureProvider.java:103)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.notifyModelListeners(XtextDocument.java:219)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.notifyModelListenersOnUiThread(XtextDocument.java:568)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:541)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:496)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:135)
	at yyyyy.ZZZZZZZZZ.documentChanged(GeneratedCodeAnnotationModel.java:178)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged2(AbstractDocument.java:744)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:713)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:697)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:771)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.access$9(XtextDocument.java:1)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$3.run(XtextDocument.java:728)
	at org.eclipse.xtext.ui.util.DisplayRunnable.syncExec(DisplayRunnable.java:35)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.fireDocumentChanged(XtextDocument.java:730)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1102)
```

**Comment by cdietrich** [comment]
increasing the delay e.g. setDelay(5000); seems to increase the likelyhood of the problem

**Comment by cdietrich** [comment]
=> in general it is a bad idea to call readonly in an IDocumentListener

**Comment by rytina** [comment]
> 
> 
> => in general it is a bad idea to call readonly in an IDocumentListener

Why? Is this documented somewhere?

**Comment by cdietrich** [comment]
no its not. but right now you will always run into this problem is you directly or indirectly call xtextdocument.readonly from a idocumentlistener

**Comment by rytina** [comment]
When I understood you correctly, the problem is that when a document listener is running before the reconciler it updates the document although the method is intended to be "readOnly". Isn't that a bug?

**Comment by cdietrich** [comment]
There is a problem but we don’t have a solution yet. The reasonless has the problem that it works on an outdated model

**Comment by rytina** [comment]
Okey, let's discuss this offline

**Comment by cdietrich** [comment]
did some more debugging.
if DocumentLineDiffer runs after another listner
that triggers outdated date and thus folding. then
the folding changes seem to run on an outdated projection annotation model
which then leads to the wired side effects.

i still dont have any clue what the proper order of the anntation listeners is.
in the ok case (reconciler job runs before other readonly-calling document listener)

i also dont know why it works properly if the readonly happens later

**Comment by cdietrich** [comment]
if the reconciler can properly care about the update then it will schedule this one

java.lang.Exception
	at org.eclipse.jface.text.source.projection.ProjectionViewer$AnnotationModelListener.processModelChanged(ProjectionViewer.java:118)
	at org.eclipse.jface.text.source.projection.ProjectionViewer$AnnotationModelListener.modelChanged(ProjectionViewer.java:114)
	at org.eclipse.jface.text.source.AnnotationModel.fireModelChanged(AnnotationModel.java:590)
	at org.eclipse.jface.text.source.AnnotationModel$InternalModelListener.modelChanged(AnnotationModel.java:255)
	at org.eclipse.jface.text.source.AnnotationModel.fireModelChanged(AnnotationModel.java:590)
	at org.eclipse.jface.text.source.AnnotationModel.fireModelChanged(AnnotationModel.java:556)
	at org.eclipse.jface.text.source.projection.ProjectionAnnotationModel.modifyAnnotations(ProjectionAnnotationModel.java:188)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingStructureProvider.updateFoldingRegions(DefaultFoldingStructureProvider.java:215)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingStructureProvider.calculateProjectionAnnotationModel(DefaultFoldingStructureProvider.java:150)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingStructureProvider.modelChanged(DefaultFoldingStructureProvider.java:104)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.notifyModelListeners(XtextDocument.java:221)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.lambda$1(XtextDocument.java:605)
	at org.eclipse.xtext.util.concurrent.IReadAccess.lambda$tryReadOnly$0(IReadAccess.java:56)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:554)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:526)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:137)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:52)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.lambda$0(XtextDocument.java:604)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3812)

which will run once the LineDiffer has already run
