### ISSUE TITLE
Highlighting trapped in a infinite loop, client almost dead.

### ISSUE THREAD

**Issue by glandon** [eclipse/xtext-eclipse#1612]
I just edit my script content, cause it not be valid, then trapped in to infinite loop.

```
let bx,wx = xshape ，<---
```
Append any character at the end of statement, will result in this loop.

```Java
override protected addLocalToCurrentScope(XVariableDeclaration localVariable, ITypeComputationState state) {
	super.addLocalToCurrentScope(localVariable, state)
       if (localVariable instanceof JpyLetVarDeclaration) {
		for (other : localVariable.other) {
			super.addLocalToCurrentScope(other, state)
		}
	}
}
```

``` java
public class DefaultSemanticHighlightingCalculator

protected void highlightElementRecursively(EObject element, IHighlightedPositionAcceptor acceptor,
			CancelIndicator cancelIndicator) {
		TreeIterator<EObject> iterator = EcoreUtil2.eAll(element);
		while (iterator.hasNext()) {
			EObject object = iterator.next();
			if (highlightElement(object, acceptor, cancelIndicator)) {
				iterator.prune();
			}
		}
	}
```

!STACK 0
java.lang.IllegalStateException: Cannot replace scope that was never recorded
	at org.eclipse.xtext.xbase.typesystem.internal.FeatureScopeTracker.replacePreviousExpressionScope(FeatureScopeTracker.java:77)
	at org.eclipse.xtext.xbase.typesystem.internal.ResolvedTypes.replacePreviousExpressionScope(ResolvedTypes.java:1503)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractTypeComputationState.rewriteScope(AbstractTypeComputationState.java:620)
	at org.eclipse.xtext.xbase.typesystem.computation.XbaseTypeComputer.addLocalToCurrentScope(XbaseTypeComputer.java:520)
	at cn.simbaba.compiler.typesystem.JpyTypeComputer.addLocalToCurrentScope(JpyTypeComputer.java:118)
	at org.eclipse.xtext.xbase.typesystem.computation.XbaseTypeComputer.addLocalToCurrentScope(XbaseTypeComputer.java:514)
	at org.eclipse.xtext.xbase.typesystem.computation.XbaseTypeComputer._computeTypes(XbaseTypeComputer.java:485)
	at org.eclipse.xtext.xbase.typesystem.computation.XbaseTypeComputer.computeTypes(XbaseTypeComputer.java:119)
	at org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsTypeComputer.computeTypes(XbaseWithAnnotationsTypeComputer.java:47)
	at cn.simbaba.compiler.typesystem.JpyTypeComputer.computeTypes(JpyTypeComputer.java:94)

**Comment by szarnekow** [comment]
> JpyLetVarDeclaration

@simboss this is certainly custom code. I'm afraid without a reproducible, self contained example there is not much that can be done about it. I suspect the problem is burried somewhere in your customizations.

**Comment by glandon** [comment]
I add a check, the infinite loop issue resolved, but i still think prune not worked as good enough.
Thank you.

``` java
if (localVariable.right === null) {
	return;
}
for (other : localVariable.other) {
	super.addLocalToCurrentScope(other, state)
}
```

**Comment by glandon** [comment]
This infinite code refered from jbase, I can close this , but maybe an issue.

**Comment by miklossy** [comment]
> This infinite code refered from jbase, I can close this , but maybe an issue.

CC @LorenzoBettini
