### ISSUE TITLE
Tests on latest hang

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1698]
Tests on latest hang

have no idea why

https://ci.eclipse.org/xtext/job/xtext-eclipse/job/master/1523/console

**Comment by cdietrich** [comment]
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=574615

**Comment by cdietrich** [comment]
cannot reproduce on mac.

**Comment by cdietrich** [comment]
[hang.jstack.txt](https://github.com/eclipse/xtext-eclipse/files/6754041/hang.jstack.txt)

**Comment by iloveeclipse** [comment]
```
"main" #1 prio=6 os_prio=0 cpu=1512,23ms elapsed=60,57s tid=0x00007f2f00016800 nid=0x23ca runnable  [0x00007f2f05637000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_events_pending(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4590)
	at org.eclipse.ui.application.WorkbenchAdvisor.openWindows(WorkbenchAdvisor.java:772)
	at org.eclipse.ui.internal.Workbench$20.runWithException(Workbench.java:1653)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:6011)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
```
This looks like SWT/GTK3 issue. Which GTK 3 is installed, and what is the difference to all other tests in the config?

**Comment by cdietrich** [comment]
here is another one

[new.jstack.log](https://github.com/eclipse/xtext-eclipse/files/6754090/new.jstack.log)

**Comment by cdietrich** [comment]
this is what i see in my vm

```
[dietrich@localhost xtext-eclipse]$ rpm -qa | grep -i gtk3
libcanberra-gtk3-0.30-22.fc32.x86_64
webkit2gtk3-jsc-2.30.6-1.fc32.x86_64
ibus-gtk3-1.5.22-7.fc32.x86_64
spice-gtk3-0.39-1.fc32.x86_64
gtk3-3.24.28-2.fc32.x86_64
webkit2gtk3-2.30.6-1.fc32.x86_64
libappindicator-gtk3-12.10.0-28.fc32.x86_64
libreoffice-gtk3-6.4.7.2-5.fc32.x86_64
libdbusmenu-gtk3-16.04.0-15.fc32.x86_64
PackageKit-gtk3-module-1.1.13-3.fc32.x86_64
libindicator-gtk3-12.10.1-17.fc32.x86_64
```

is there another command to tetermine gtk version?

**Comment by iloveeclipse** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=574119 ?

**Comment by cdietrich** [comment]
fixed with revert on platform
