### ISSUE TITLE
Resource Leak in XbaseInformationControl

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1781]
```
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.TextLayout.<init>(TextLayout.java:83)
	at org.eclipse.xtext.xbase.ui.hover.XbaseInformationControl.createTextLayout(XbaseInformationControl.java:572)
	at org.eclipse.xtext.xbase.ui.hover.XbaseInformationControl.createContent(XbaseInformationControl.java:176)
	at org.eclipse.jface.text.AbstractInformationControl.create(AbstractInformationControl.java:437)
	at org.eclipse.xtext.xbase.ui.hover.XbaseInformationControl.<init>(XbaseInformationControl.java:96)
	at org.eclipse.xtext.xbase.ui.hover.XbaseHoverProvider$XbaseHoverControlCreator$1.<init>(XbaseHoverProvider.java:389)
```

**Comment by cdietrich** [comment]
dupes #1699
