### ISSUE TITLE
some tests dont work on latest and build does not fail

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1842]
https://ci.eclipse.org/xtext/job/xtext-eclipse/job/master/2430/consoleFull
```
0:18:03  [INFO] Executing Test Runtime with timeout 2400, logs (if any) will be placed at: /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/target/work/data/.metadata/.log
10:18:03  [INFO] Command line:
10:18:03  	[/opt/tools/java/temurin/jdk-17/latest/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -Xmx1500m, -Dosgi.clean=true, -jar, /home/jenkins/agent/workspace/xtext-eclipse_master/$VALUE/p2/osgi/bundle/org.eclipse.equinox.launcher/1.6.400.v20210924-0641/org.eclipse.equinox.launcher-1.6.400.v20210924-0641.jar, -data, /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/target/work/data, -install, /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/target/work, -configuration, /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/target/surefire.properties, -pluginCustomization, /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/../releng/org.eclipse.xtext.tycho.tests.parent/pluginCustomization.ini, -timeout, 2400000]
10:18:18  java.lang.RuntimeException: Bundle org.eclipse.xtext.xbase.ui.tests is not found
10:18:18  	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundle(OsgiSurefireBooter.java:221)
10:18:18  	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundleClassLoader(OsgiSurefireBooter.java:197)
10:18:18  	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.createCombinedClassLoader(OsgiSurefireBooter.java:139)
10:18:18  	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:128)
10:18:18  	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication$1.run(AbstractUITestApplication.java:37)
10:18:18  	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
10:18:18  	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
10:18:18  	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5004)
10:18:18  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4484)
10:18:18  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
10:18:18  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
10:18:18  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
10:18:18  	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
10:18:18  	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
10:18:18  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
10:18:18  	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
10:18:18  	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
10:18:18  	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
10:18:18  	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:29)
10:18:18  	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:122)
10:18:18  	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:35)
10:18:18  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
10:18:18  	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:36)
10:18:18  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
10:18:18  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
10:18:18  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
10:18:18  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
10:18:18  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:18:18  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10:18:18  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:18:18  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:18:18  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
10:18:18  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
10:18:18  	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
10:18:18  	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
10:18:18  [ERROR] There are test failures.
10:18:18  
10:18:18  Please refer to /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/target/surefire-reports for the individual test results.
10:18:18  [INFO] 
10:18:18  [INFO] --- maven-install-plugin:2.3.1:install (default-install) @ org.eclipse.xtext.xbase.ui.tests 
```

```
!SESSION 2022-04-22 11:22:19.756 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_312
java.vendor=Temurin
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/target/surefire.properties -pluginCustomization /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/../releng/org.eclipse.xtext.tycho.tests.parent/pluginCustomization.ini -timeout 2400000
Command-line arguments:  -data /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/target/work/data -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/target/surefire.properties -pluginCustomization /home/jenkins/agent/workspace/xtext-eclipse_master/org.eclipse.xtext.xbase.ui.tests/../releng/org.eclipse.xtext.tycho.tests.parent/pluginCustomization.ini -timeout 2400000

!ENTRY org.eclipse.jdt.launching.macosx 4 0 2022-04-22 11:22:21.552
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jdt.launching.macosx [231]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.os=macosx)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1613)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.jdt.launching.ui.macosx 4 0 2022-04-22 11:22:21.554
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jdt.launching.ui.macosx [232]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.os=macosx)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1613)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.compare.win32 4 0 2022-04-22 11:22:22.148
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.compare.win32 [310]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.os=win32)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1613)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.core.resources 2 10035 2022-04-22 11:31:34.265
!MESSAGE The workspace will exit with unsaved changes in this session.

```
have no idea why tycho does not mark the tests as failed then

**Comment by laeubi** [comment]
Calling Maven with ARGS: --batch-mode --update-snapshots --fae **-Dmaven.test.failure.ignore=true** -Declipse.p2.mirrors=false -Dtycho.disableP2Mirrors=true

I think it is meant that there is an additional step collecting all unit tests and then fail the build on the CI level showing a nice statistic about all failed/successful tests.

**Comment by laeubi** [comment]
But obvious if you request to *not fail* then tycho can't do anything here regardless of version :-)

**Comment by cdietrich** [comment]
I will try to do software archeology why it is done this way @kthoms @szarnekow any idea

**Comment by szarnekow** [comment]
I'd think what we really want is `--fail-at-end ` instead of test.failure.ignore.

**Comment by laeubi** [comment]
FYI @jonahgraham 
I have created https://gitlab.ow2.org/asm/asm/-/issues/317975 as I think asm is probably missing some useconstraints
@bjhargrave @tjwatson can anyone maybe take a look at the asm issue I sadly don't fully understand how they generate the manifest and maybe my assumption is wrong here, but it seem asm has missing use-constraints that leads to this state

**Comment by bjhargrave** [comment]
I don't have a gitlab account for ow2, so I will reply here. The Export-Package looks fine. You need to look in the class files. While SignatureVisitor uses OpCodes, all the references are to constants and the compiler inlines the constant references in the generated class file so there is no class file reference from SignatureVisitor to OpCodes and thus no uses constraint for Bnd to infer from the code.

**Comment by laeubi** [comment]
Thanks for the check, I have copied you comment there for reference, I think I was looking at the wron place, from the xtext issue the error is:

```
Chain 1:
  org.eclipse.pde.api.tools [osgi.identity; osgi.identity="org.eclipse.pde.api.tools"; type="osgi.bundle"; version:Version="1.2.900.v20220411-2005"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.objectweb.asm)(&(bundle-version>=9.3.0)(!(bundle-version>=10.0.0))))
     |
    provide: osgi.wiring.bundle: org.objectweb.asm
  org.objectweb.asm [osgi.identity; osgi.identity="org.objectweb.asm"; type="osgi.bundle"; version:Version="9.3.0"]

Chain 2:
  org.eclipse.pde.api.tools [osgi.identity; osgi.identity="org.eclipse.pde.api.tools"; type="osgi.bundle"; version:Version="1.2.900.v20220411-2005"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.objectweb.asm.tree)(&(bundle-version>=9.2.0)(!(bundle-version>=10.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="9.2.0.v20210813-1119"; osgi.wiring.bundle="org.objectweb.asm.tree"
  org.objectweb.asm.tree [osgi.identity; osgi.identity="org.objectweb.asm.tree"; type="osgi.bundle"; version:Version="9.2.0.v20210813-1119"]
    import: (&(osgi.wiring.package=org.objectweb.asm)(&(version>=9.2.0)(!(version>=9.3.0))))
     |
    export: osgi.wiring.package: org.objectweb.asm
  org.objectweb.asm [osgi.identity; osgi.identity="org.objectweb.asm"; type="osgi.bundle"; version:Version="9.2.0.v20210813-1119"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

And there is seems it requires some **org.objectweb.asm.tree** and conflicts with **org.objectweb.asm** so maybe `org.eclipse.pde.api.tools` is the culprit here and `asm` is not to blame?

**Comment by bjhargrave** [comment]
You seem to getting burned by Require-Bundle.

> require: (&(osgi.wiring.bundle=org.objectweb.asm)(&(bundle-version>=9.3.0)(!(bundle-version>=10.0.0))))

> require: (&(osgi.wiring.bundle=org.objectweb.asm.tree)(&(bundle-version>=9.2.0)(!(bundle-version>=10.0.0))))

Using Import-Package for asm will help.

**Comment by laeubi** [comment]
I also thought so, strange enough it says:

> it is exposed to package 'org.objectweb.asm' from resources org.objectweb.asm [osgi.identity; osgi.identity="org.objectweb.asm"; type="osgi.bundle"; version:Version="9.3.0"] and org.objectweb.asm [osgi.identity; osgi.identity="org.objectweb.asm"; type="osgi.bundle"; version:Version="9.2.0.v20210813-1119"] via two dependency chains.

so should that not mean its a split package and importing both bundles should be fine, but I assume both packages have to match in version to qualify as a valid split package.

I'll see if I can find where this is used in the API tools, but I'm neither familiar with API tools nor its ASM usage...

**Comment by bjhargrave** [comment]
> so should that not mean its a split package and importing both bundles should be fine

No, the message says some chain requires both `org.objectweb.asm` and `org.objectweb.asm.tree` bundles and each bundle exports package `org.objectweb.asm`. This means being exposed to two instances of the packages which is a no-no.

**Comment by cdietrich** [comment]
if the export is versioned should that work?
or is the problem that our require bundle constraint pulls asm 9.2
whilst pde needs both tree and asm?

**Comment by bjhargrave** [comment]
`org.eclipse.pde.api.tools` requires bundle `org.objectweb.asm;bundle-version=9.3.0` which exports `org.objectweb.asm;version=9.3.0`.

`org.eclipse.pde.api.tools` also requires bundle `org.objectweb.asm.tree;bundle-version=9.2.0` which imports `org.objectweb.asm;version=[9.2.0,9.3.0)`.

So the import cannot be satisfied by the earlier export (version range mismatch) So now the resolver wants an exporter to match `org.objectweb.asm;version=[9.2.0,9.3.0)` and it brings in `org.objectweb.asm;bundle-version=9.2.0` which exports a matching version of `org.objectweb.asm`. 

Since `org.eclipse.pde.api.tools` did not itself Require-Bundle `org.objectweb.asm;bundle-version=9.2.0` (since it required `org.objectweb.asm;bundle-version=9.3.0`) there is no combining of the `org.objectweb.asm` packages.

The issue seems to be `org.eclipse.pde.api.tools` requiring different versions for `org.objectweb.asm` and `org.objectweb.asm.tree`.

**Comment by laeubi** [comment]
Strange that this was not discovered earlier I have opened https://github.com/eclipse-pde/eclipse.pde/issues/42

**Comment by cdietrich** [comment]
with the upstream fix we are green again.
will pr the removal of test failure ignore anyway.
will also think about getting rid of the pde api dep alltogether

**Comment by laeubi** [comment]
Great, thanks for verification.

**Comment by cdietrich** [comment]
removed the test failure ignore

**Comment by cdietrich** [comment]
also remove the dependency to pde.api

**Comment by cdietrich** [comment]
thus consider this as done
