### ISSUE TITLE
Races in Storage2UriMapperJavaImpl

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1853]
we observe the following races in `Storage2UriMapperJavaImpl`

initialize race

```
Storage2UriMapperJavaImpl.clearCache(IJavaProject, Set<String>)
Storage2UriMapperJavaImpl.updateCache(IJavaProject)
Storage2UriMapperJavaImpl$3.run(IProgressMonitor)
Storage2UriMapperJavaImpl.doInitializeCache()	
Storage2UriMapperJavaImpl.initializeCache(boolean)
Storage2UriMapperJavaImplelementChanged(ElementChangedEvent)	
```

```
Storage2UriMapperJavaImpl.clearCache(IJavaProject, Set<String>)
Storage2UriMapperJavaImpl.updateCache(IJavaProject)
Storage2UriMapperJavaImpl$3.run(IProgressMonitor)
Workspace.run(ICoreRunnable, ISchedulingRule, int, IProgressMonitor)
Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor)
Storage2UriMapperJavaImpl.doInitializeCache()	
Storage2UriMapperJavaImpl$2.run()	
Thread.run()	
```

read on non initialized

```
Storage2UriMapperJavaImpl.getCachedData(Storage2UriMapperJavaImplCopy.java)
	at .Storage2UriMapperJavaImp.getData(Storage2UriMapperJavaImplCopy.java)
	at Storage2UriMapperJavaImpl.getAllEntries(Storage2UriMapperJavaImplCopy.java)
	at org.eclipse.xtext.builder.impl.javasupport.JdtToBeBuiltComputer.updateProject(JdtToBeBuiltComputer.java:123)
```
might be called before
```
Storage2UriMapperJavaImpl.getCachedData(Storage2UriMapperJavaImplCopy.java)
	at Storage2UriMapperJavaImpl.updateCache(Storage2UriMapperJavaImplCopy.java)
	at Storage2UriMapperJavaImpl.elementChanged(Storage2UriMapperJavaImplCopy.java)
	at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1755)
```

in both cases the clearCache will remove stuff that is in toBeKept with the same path/uriPrefix but a different PackageFragmentRootData.

this will lead to follow up errors as there is no IContainer for the Jar, and thus visibleContainer calls etc wont work

**Comment by cdietrich** [comment]
Naive fix ideas:
- implement equals and hashcode in packagefragmentrootdata, cannot test this in my scenario as the constructor call is not customizable in current released xtext versions

- solve the init problem

```
			if (workspace.isTreeLocked()) {
				runnable.run(null);
			} else {
				ISchedulingRule currentRule = Job.getJobManager().currentRule();
				ISchedulingRule rule = null;
				if (currentRule == null) {
					rule = workspace.getRoot();
				}
				workspace.run(runnable, rule, IWorkspace.AVOID_UPDATE, null);
			}
```

- solve the read problem: dont cache if not inited
```
	protected PackageFragmentRootData getData(IPackageFragmentRoot root) {
		final boolean isCachable = shouldHandle(root);
		if (isCachable && isInitialized) {
			return getCachedData(root);
		}
		PackageFragmentRootData data = initializeData(root);
		return data;
	}
```


of course a complete overhaul of the complete thing would be much better, but i have zero clue where to start

**Comment by cdietrich** [comment]
what is also is bogus: if we want to run with workspace lock,
but NotificationManager.NotifyJob does not use any, 
this will be a problem too

**Comment by cdietrich** [comment]
maybe we also need to double check before put
```
synchronized (cachedPackageFragmentRootData) {
                if (!cachedPackageFragmentRootData.containsKey(path)) {
                    cachedPackageFragmentRootData.put(path, data);
                } else {
                    data = cachedPackageFragmentRootData.get(path);
                }
            }
```
@szarnekow what do you think?

**Comment by szarnekow** [comment]
> maybe we also need to double check before put
> 
> ```
> synchronized (cachedPackageFragmentRootData) {
>                 if (!cachedPackageFragmentRootData.containsKey(path)) {
>                     cachedPackageFragmentRootData.put(path, data);
>                 } else {
>                     data = cachedPackageFragmentRootData.get(path);
>                 }
>             }
> ```
> 
> @szarnekow what do you think?
> 
> but this still might be a problem if two updateCache runs in parallel => i really think we need a complete overhaul. unfortunately i dont know why we currently do all the fine grained locks. i assume it is to avoid deadlocks or long runtimes

The fine grained locks are present to avoid a long running blocking operation which might be problematic for large workspaces (law of big numbers ...). I've seen workspaces with 30mins of build time for JDT alone with hundreds and hundreds of jars in the target platform. If we block on these, it might be problematic.

The fine grained locks might be avoidable if we'd use a persistent map instead of a regular map. That would still allow reads while processing. Or we collect the modifications that are supposed to happen and use a StampedReference to make sure we modify only if it's still the same state.

> maybe we also need to double check before put

The proposal looks like a `putIfAbsent`. Might be worthwhile to use that, yes.

**Comment by cdietrich** [comment]
```
java.util.ConcurrentModificationException at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:746) at org.eclipse.xtext.ui.resource.Storage2UriMapperJavaImpl.getStorages(Storage2UriMapperJavaImpl.java:393) at org.eclipse.xtext.ui.resource.Storage2UriMapperImpl$2$1.apply(Storage2UriMapperImpl.java:139) at org.eclipse.xtext.ui.resource.Storage2UriMapperImpl$2$1.apply(Storage2UriMapperImpl.java:1) at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:614) at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1333) at org.eclipse.xtext.ui.resource.Storage2UriMapperImpl.getStorages(Storage2UriMapperImpl.java:224) at org.eclipse.xtext.ui.resource.Storage2UriMapperImpl.getStorages(Storage2UriMapperImpl.java:212) at org.eclipse.xtext.ui.editor.WorkspaceEncodingProvider.getEncoding(WorkspaceEncodingProvider.java:63) at org.eclipse.xtext.resource.XtextResource.getEncoding(XtextResource.java:206) at org.eclipse.xtext.resource.XtextResource.createReader(XtextResource.java:192) at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:178) at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLoad(LazyLinkingResource.java:115) at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563) at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342) at org.eclipse.xpect.runner.XpectRunner.loadXpectResource(XpectRunner.java:188) at org.eclipse.xpect.runner.XpectRunner.createChild(XpectRunner.java:80) at org.eclipse.xpect.runner.XpectRunner.createChildren(XpectRunner.java:97) at org.eclipse.xpect.runner.XpectRunner.getChildren(XpectRunner.java:150) at 
```
