### ISSUE TITLE
Oomph + org.eclipse.wst.sse.core + icu

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1899]
we install org.eclipse.wst.sse.core via oomph,
this leads to problems with icu

```
java.lang.NoClassDefFoundError: com/ibm/icu/util/StringTokenizer
	at org.eclipse.wst.sse.core.utils.StringUtils.unpack(StringUtils.java:777)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.getScannedProjects(TaskScanningJob.java:295)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.projectHasNotBeenFullyScanned(TaskScanningJob.java:152)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.addProject(TaskScanningJob.java:118)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningScheduler.enqueue(TaskScanningScheduler.java:137)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningScheduler.startup(TaskScanningScheduler.java:117)
	at org.eclipse.wst.sse.core.internal.SSECorePlugin.lambda$0(SSECorePlugin.java:96)
	at org.eclipse.core.runtime.jobs.Job$1.run(Job.java:166)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.util.StringTokenizer cannot be found by org.eclipse.wst.sse.core_1.2.800.v202207121749
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:487)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 9 more
```
dont know if this also happens in a plain and fresh oomphed env

**Comment by cdietrich** [comment]
![Bildschirmfoto vom 2022-08-26 19-56-30](https://user-images.githubusercontent.com/238736/186964039-8432d10c-8929-4a16-8b52-c00d71cde1a7.png)
@merks do you have on overview what the latest plan for icu is?

cc @nitind

**Comment by cdietrich** [comment]
osgi console says

```
osgi.wiring.package; bundle-symbolic-name="com.ibm.icu"; bundle-version:Version="67.1.0"; version:Version="0.0.0"; osgi.wiring.package="com.ibm.icu.util"<com.ibm.icu_67.1.0 [10655]>
  org.eclipse.wst.json.bower.core_1.0.0.v201901071922 [580] imports
  org.eclipse.wst.json.npm.ui_1.0.100.v201904210526 [6939] imports
  org.eclipse.m2e.archetype.common_3.2.1.20220620-0741 [10871] imports
  org.eclipse.jdt.junit_3.15.0.v20220815-1918 [10761] imports
  org.eclipse.team.cvs.ui_3.5.0.v20210426-0843 [6862] imports
  org.eclipse.jdt.debug.ui_3.12.800.v20220813-1738 [10758] imports
  org.eclipse.wst.json.core_1.1.0.v201901152013 [782] imports
  org.eclipse.wst.json.ui_1.0.600.v202103121626 [6940] imports
  org.eclipse.jem.util_2.1.300.v202103232321 [6708] imports
  org.eclipse.wst.json.jshint.core_1.0.1.v201908281850 [6937] imports
  org.eclipse.buildship.ui_3.1.6.v20220511-1359 [10053] imports
  org.eclipse.wst.json.jshint.ui_1.0.200.v201904210526 [6938] imports
  org.eclipse.wst.json.npm.core_1.0.0.v201901071922 [587] imports
  org.eclipse.wst.json.eslint.core_1.0.0.v201901071922 [583] imports
  org.eclipse.wst.json.schemaprocessor_1.0.200.v201901071922 [589] imports
  org.eclipse.wst.json.bower.ui_1.0.200.v201904210526 [6935] imports
  org.eclipse.jdt.ui_3.27.0.v20220815-0907 [10767] imports
  org.eclipse.wst.json.eslint.ui_1.0.200.v201904210526 [6936] imports
```

https://download.eclipse.org/releases/2022-09/202208261000/plugins/
contains both icu bundles

**Comment by cdietrich** [comment]
after uninstalling com.ibm.icu.base  the wst stuff can no longer be resolved

**Comment by cdietrich** [comment]
looks also like the wst version in eclipse is old and oomph does not pull newer. need to find out why

**Comment by cdietrich** [comment]
guess we have to reoomph from scratch to get rid of these wired effects

**Comment by cdietrich** [comment]
https://download.eclipse.org/releases/2022-09/202208261000/plugins/
has old timestamps for draw2d
so https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/476#issuecomment-1214712245 does not seem to have landed for gef

**Comment by merks** [comment]
The stack trace you show looks like the one we got when the platform switched to version 71 for a while but it caused a bunch of problems so they switched back.   Note that the unqualified version  67.1.0 is less that the Orbit one with the version qualifier so the latter will tend to get installed.  They should have identical content and should not cause the type of problem in the stack trace.

**Comment by merks** [comment]
Here's the problem.  The platform includes the maven version in their feature while RCP includes the Orbit version in their feature.   All package imports with version restrictions resolve only to the Orbit version because the Maven version doesn't have versioned packages:

![image](https://user-images.githubusercontent.com/208716/187019077-d711428d-3e44-47b9-b6a3-c8d841557580.png)

So it's totally a mess and there are no good plans for how to get rid of the mess, except maybe to get rid of the bundle completely...

**Comment by cdietrich** [comment]
will close. problem did not reoccur
