### ISSUE TITLE
Error when building the xtext source code

### ISSUE THREAD

**Issue by penghzhang** [eclipse/xtext-eclipse#286]
Hi,
Today, i downloaded the xtext source code from git and tried to build it, but there is something wrong. Xtext version is 2.10.0, My computer is Windows 7, JDK is 1.8.0_131, the way to build the project is executing the command 'mvn -X clean compile -Pinclude-unpublished -Dmaven.test.skip=true -Dmaven.javadoc.skip=true' under the directory of 'xtext-2.10.0\maven\org.eclipse.xtext.tycho.parent'.
The error log is as follow:
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.23.1:compile (default-compile) on project org.e
clipse.xtext.xbase.ui: Compilation failure: Compilation failure:
[ERROR] D:\Souce Code\xtext-2.10.0\plugins\org.eclipse.xtext.xbase.ui\xtend-gen\org\eclipse\xtext\xbase\ui\editor\XbaseE
ditorInputRedirector.java:[53]
[ERROR] final IJavaElement adapter = it.<IJavaElement>getAdapter(IJavaElement.class);
[ERROR] ^^^^^^^^^^
[ERROR] The method getAdapter(Class) of type IAdaptable is not generic; it cannot be parameterized with arguments <IJava
Element>
[ERROR] 1 problem (1 error)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0
.23.1:compile (default-compile) on project org.eclipse.xtext.xbase.ui: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: copied.org.apache.maven.plugin.CompilationFailureException: Compilation failure
        at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:420)
        at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute(AbstractOsgiCompilerMojo.java:293)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.eclipse.xtext.xbase.ui

From the log, i think it is the bug of the xtend code, am I right? Could help me analyze log and give me some suggestion? 
Hope for your reply!

**Comment by cdietrich** [comment]
This looks like the target platform in eclipse and tycho don't match

Can you revert local changes and try again

**Comment by penghzhang** [comment]
I have reverted my changes and I built the code in the terminal instead of in eclipse, and my environment is as follow:
Xtext version is 2.10.0, 
My computer is Windows 7, 
JDK is 1.8.0_131, 
Maven version:3.2.3
the way to build the project is executing the command 'mvn -X clean compile -Pinclude-unpublished -Dmaven.test.skip=true -Dmaven.javadoc.skip=true' under the directory of 'xtext-2.10.0\maven\org.eclipse.xtext.tycho.parent'.

Hope for your suggestion!
Thanks!!!

**Comment by cdietrich** [comment]
Since I don't know the 210 build I have no idea. 

Does the code contain a cast or not? When the build is run?

**Comment by penghzhang** [comment]
- Does the code contain a cast or not?
The code doesn't contain a cast;
- When the build is run?
I manually execute the above command in the terminal of cmd of windows 7.

**Comment by cdietrich** [comment]
Isn't the code checked in? Are there changes after build

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext/blob/v2.10.0/plugins/org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/editor/XbaseEditorInputRedirector.java#L50

=> you need to make sure that e.g. "luna" is picked as target platform

**Comment by penghzhang** [comment]
Thanks for your help! Now I can build the project successfully. But I still have an doubt:  what does the 'target platform' mentioned before mean?  eclipse platform or something else?
Hope for your reply!

**Comment by cdietrich** [comment]
it is a eclipse plugin development term.
it basically describes against which eclipse version with which plugins you are developing your plugins (in this case xtext) against.

since the api inside eclipse changes and you use a new eclipse (e.g. neon or mars) and develop without setting the target platform to e.g. the target files from xtext, then it might happen that generators or auto format will produce code that is not compileable.

in your case there was a change in the api of get Adapter that returned Object in oder Versions and now an object of the type of the class you ass

=> xtend generated code differs

**Comment by penghzhang** [comment]
Thanks for your answer and I understand it. 
Thanks again!
