### ISSUE TITLE
Error logged during rename refactoring

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-eclipse#416]
In xtext-eclipse workspace during re-naming errors are logged.

E.g. in AbstractIgnoreCaseLinkingTestLanguage rename Element to Element3

org.eclipse.xtext.ui.refactoring.impl.EmfResourceReferenceUpdater  - Couldn't find source element platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/AbstractIgnoreCaseLinkingTestLanguage.genmodel#//ignoreCaseLinkingTest/Element/reference in platform:/resource/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/linking/AbstractIgnoreCaseLinkingTestLanguage.genmodel

Also crossref [Element] is not updated:
```
Element3:
    name=ID reference=[Element]? '{'
    	elements += Element3*
    '}'
;
```

**Comment by dhuebner** [comment]
Full stacktrace:
```

java.lang.IllegalStateException: getReferenceDescriptions platform:/resource/org.eclipse.xtext/org/eclipse/xtext/Xtext.genmodel
	at org.eclipse.xtext.builder.clustering.CopiedResourceDescription.getReferenceDescriptions(CopiedResourceDescription.java:84)
	at org.eclipse.xtext.findReferences.ReferenceFinder.findReferencesInDescription(ReferenceFinder.java:162)
	at org.eclipse.xtext.findReferences.ReferenceFinder.findReferences(ReferenceFinder.java:156)
	at org.eclipse.xtext.findReferences.ReferenceFinder.findAllReferences(ReferenceFinder.java:181)
	at org.eclipse.xtext.ui.editor.findrefs.DelegatingReferenceFinder.findAllReferences(DelegatingReferenceFinder.java:62)
	at org.eclipse.xtext.xtext.ui.refactoring.RuleOverrideUtil.getOverridingRules(RuleOverrideUtil.java:70)
	at org.eclipse.xtext.xtext.ui.refactoring.OverridingRuleRefactoringParticipant.getRenamedElementsOrProxies(OverridingRuleRefactoringParticipant.java:33)
	at org.eclipse.xtext.ui.refactoring.impl.AbstractProcessorBasedRenameParticipant.createRenameElementContexts(AbstractProcessorBasedRenameParticipant.java:212)
	at org.eclipse.xtext.ui.refactoring.impl.AbstractProcessorBasedRenameParticipant.getRenameProcessors(AbstractProcessorBasedRenameParticipant.java:99)
	at org.eclipse.xtext.ui.refactoring.impl.AbstractProcessorBasedRenameParticipant.initialize(AbstractProcessorBasedRenameParticipant.java:85)
	at org.eclipse.ltk.core.refactoring.participants.RefactoringParticipant.initialize(RefactoringParticipant.java:105)
	at org.eclipse.ltk.core.refactoring.participants.ParticipantExtensionPoint.getParticipants(ParticipantExtensionPoint.java:100)
	at org.eclipse.ltk.core.refactoring.participants.ParticipantManager.loadRenameParticipants(ParticipantManager.java:74)
	at org.eclipse.ltk.core.refactoring.participants.ParticipantManager.loadRenameParticipants(ParticipantManager.java:53)
	at org.eclipse.xtext.ui.refactoring.impl.RenameElementProcessor.loadParticipants(RenameElementProcessor.java:291)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:231)
	at org.eclipse.ltk.core.refactoring.Refactoring.checkAllConditions(Refactoring.java:162)
	at org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringExecuter$CheckConditionsAndCreateChangeRunnable.run(RenameRefactoringExecuter.java:145)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.xtext.ui.refactoring.ui.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:83)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)
	at org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringExecuter.execute(RenameRefactoringExecuter.java:97)
	at org.eclipse.xtext.ui.refactoring.ui.DefaultRenameSupport.startDirectRefactoring(DefaultRenameSupport.java:98)
	at org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController.startDirectRefactoring(RenameRefactoringController.java:203)
	at org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController.startRefactoring(RenameRefactoringController.java:116)
	at org.eclipse.xtext.ui.refactoring.ui.RenameLinkedMode$EditorSynchronizer.left(RenameLinkedMode.java:167)
	at org.eclipse.jface.text.link.LinkedModeModel.exit(LinkedModeModel.java:333)
	at org.eclipse.jface.text.link.LinkedModeUI$3.run(LinkedModeUI.java:1183)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4033)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)


```
