### ISSUE TITLE
Content Assist NPE after dispose

### ISSUE THREAD

**Issue by parnold-x** [eclipse/xtext-eclipse#421]
I am using the EmbeddedEditor in a Wizard
```java
XtextResourceSet resourceSet = (XtextResourceSet) injector.getInstance(XtextResourceSetProvider.class).get(null);
res = (XtextResource) resourceSet.createResource(URI.createURI("synthetic:/model."+ext));
EmbeddedEditorFactory factory = injector.getInstance(EmbeddedEditorFactory.class);
embeddedEditor = factory.newEditor(new IEditedResourceProvider() {
      @Override
       public XtextResource createResource() {
		return res;
	}
}).withParent(parent);
embeddedEditorModelAccess = embeddedEditor.createPartialEditor();
embeddedEditorModelAccess.updateModel("");
```

The content assist works fine at the first try. But after disposing the wizard and reopening it I get a NPE when accessing the content assist.

```java
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser.getFollowElements(AbstractContentAssistParser.java:342)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser.getFollowElements(AbstractContentAssistParser.java:337)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser.getFollowElements(AbstractContentAssistParser.java:331)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser.getFollowElements(AbstractContentAssistParser.java:381)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.createContextsForLastCompleteNode(ContentAssistContextFactory.java:278)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory.handleLastCompleteNodeIsPartOfLookahead(ContentAssistContextFactory.java:213)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$3.call(ContentAssistContextFactory.java:165)
	at org.eclipse.xtext.ide.editor.contentassist.antlr.ContentAssistContextFactory$3.call(ContentAssistContextFactory.java:162)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

The problem is that **RuleNames:getAntlrRuleName** returns null because the Rule is a different object than those in this Map. The RuleNames instance is constructed at first accessing the resource and not again if I reopen the wizard. 

**AbstractContentAssistParser:initEntryRule** will be called at the second open of the wizard 3 times. 2 times with the right ParserRule object and once with another instance.

Am I doing something wrong or is this a bug?

**Comment by cdietrich** [comment]
do you call standalonesetup somewhere?

**Comment by parnold-x** [comment]
No, the wizard is called inside a RCP.

**Comment by cdietrich** [comment]
but where does the different grammar come from that is passed to initEntryRule

**Comment by parnold-x** [comment]
It's the same Grammar but different objects. The .xtextbin resource is loaded twice.

Activator activator =Activator.getInstance();
Injector injector = activator.getInjector(Activator .ID);

**Comment by cdietrich** [comment]
but this means there are multple injectors created right?

**Comment by cdietrich** [comment]
and ususally the class is called MydslActivator

**Comment by parnold-x** [comment]
Yep. MydslActivator and the injector is cached there. So a single injector.

**Comment by cdietrich** [comment]
but then the injector should create the mydslgrammaraccess only once right?

**Comment by parnold-x** [comment]
Where can I check this? I just use the code seen in the first snippet.

**Comment by cdietrich** [comment]
simply use the debugger in the contstructor

**Comment by cdietrich** [comment]
and you are sure there are no other guys that call standalonesetup etc?

**Comment by parnold-x** [comment]
You right. Just checked. There is some code that also parses the string in some non UI plugin and there is the StandaloneSetup called. How should this work together the right way?

**Comment by cdietrich** [comment]
no code inside eclipse shall ever call standalonesetup. it will destroy injectors and emf registries
=> is this other code somehow called inside eclipse?

**Comment by parnold-x** [comment]
Ohh. Ok . That is probably the issue.
Yes. It's alsoinside  eclipse but without UI dependencies. So no dependency to the AbstractUIPlugin where the injector is cached. Should i just move this to the non UI plugin or do new injectors?

**Comment by cdietrich** [comment]
why does this tool create its own injector instead of simply getting created and injected from outside?

**Comment by parnold-x** [comment]
Probably because I do it the wrong way :) The MydslActivator which extends AbstractUIPlugin has a getInjector method which i get the injector for the EmbeddedEditor. The non UI code should just parse the string to the grammar model. How do I get the injector there?

**Comment by cdietrich** [comment]
`@Inject Injector injector` ????
but why not `@Inject thingthatineed thing` ????
what does that util do with injector

**Comment by parnold-x** [comment]
I just need the XtextResource to load the string. 
I am not really get it. I have a plugin that depends on the grammar plugin. 
I tought i can't inject there,

**Comment by cdietrich** [comment]
IResourceServiceProvider.Registry.INSTANCE.getResourceServiceProvider(URI.createURI("dumy.mydsl")).get(....) should work as well (pseudo code)
