### ISSUE TITLE
TwoProjectsTest is Flaky

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#581]
e.g.

```
Fehlermeldung

Couldn't resolve reference to Greeting 'First'. expected:<0> but was:<1>

Stacktrace

java.lang.AssertionError: 
Couldn't resolve reference to Greeting 'First'. expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.eclipse.xtext.builder.noJdt.TwoProjectsTest.testOpenAndCloseReferencedProjects(TwoProjectsTest.java:148)

```

possible cause:
 
`ProjectOpenedOrClosedListener` calls `buildScheduler.scheduleBuildIfNecessary` which calls `new BuildJob(Messages.BuildScheduler_JobName, scheduleUs).schedule();`
this job might take some time to start. so the explicit build call runs before the build scheduler job.

possible reproduction:

possible solution:

 do a join on autobuild before open call.

**Comment by cdietrich** [comment]
FIxed in 2.14
