### ISSUE TITLE
Launch as Junit test not working for junit 5

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#653]
``` 
java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:367)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:362)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:306)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:221)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:205)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.launcher.core.LauncherFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

**Comment by cdietrich** [comment]
@kthoms looks like org.junit.platform.launcher is missing a dependency after project creation with wizard/initial workflow run

**Comment by kthoms** [comment]
Works for me. Please provide detailed steps to reproduce.

What I did:
- create project with Java 8, Eclipse Plugin, Maven
- open the `org.xtext.example.mydsl.target.target` target def and set it as target platform. Note that wizard creates a target that contains also JU5 since yesterday. Might be related.
- run the build
- open MyDslParsingTest and execute it with Run As / JUnit Test

![screenshot 78](https://user-images.githubusercontent.com/265597/39815658-0b4978f2-5399-11e8-8059-f1cda2ab6a1e.png)

**Comment by cdietrich** [comment]
(1) use Photon as target in dev eclipse
(2) start runtime
(3) use wizard and create new xtext project with junit5
(4) rightclick the xtend test and run as junit
(5) see the error

**Comment by cdietrich** [comment]
![bildschirmfoto vom 2018-05-09 18-26-51](https://user-images.githubusercontent.com/238736/39826908-95e2cd84-53b6-11e8-9338-ccc28e5b207b.png)

**Comment by cdietrich** [comment]
when adding  org.junit.platform.launcher;bundle-version="1.1.0" explicit it works fine

**Comment by cdietrich** [comment]
@kthoms  Problem happens in oxygen 3a only, not in photon

**Comment by kthoms** [comment]
What if you remove the dependencies except API and add "JUnit Library" to the build path?

**Comment by cdietrich** [comment]
junit in eclipse no longer ofers to run as test and if i run old config get an error message

![j5](https://user-images.githubusercontent.com/238736/40051473-2a45e492-583b-11e8-9fbe-393f0a093898.png)

and after adding `org.junit.platform.commons;bundle-version="1.1.0",`

```
java.lang.NoClassDefFoundError: org/junit/platform/engine/EngineDiscoveryRequest
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:59)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:367)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:362)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:306)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:221)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:205)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.engine.EngineDiscoveryRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more

```

**Comment by cdietrich** [comment]
wont work with oxygen too

```
May 16, 2018 10:10:08 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.NoClassDefFoundError: org/junit/platform/engine/support/filter/ExclusionReasonConsumingFilter
	at org.junit.vintage.engine.discovery.VintageDiscoverer.createTestClassPredicate(VintageDiscoverer.java:83)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.collectTestClasses(VintageDiscoverer.java:61)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:51)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:65)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:82)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.<init>(JUnit5TestReference.java:42)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createUnfilteredTest(JUnit5TestLoader.java:73)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createTest(JUnit5TestLoader.java:63)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.loadTests(JUnit5TestLoader.java:50)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:522)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.engine.support.filter.ExclusionReasonConsumingFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

May 16, 2018 10:10:08 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.NoClassDefFoundError: org/junit/platform/engine/support/filter/ExclusionReasonConsumingFilter
	at org.junit.vintage.engine.discovery.VintageDiscoverer.createTestClassPredicate(VintageDiscoverer.java:83)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.collectTestClasses(VintageDiscoverer.java:61)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:51)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:65)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

```

**Comment by kthoms** [comment]
Should be solved by https://github.com/eclipse/xtext-eclipse/pull/673. The JUnit5 Library container will contains the dependencies for `org.junit.platform.engine` and `org.junit.platform.launcher`

<img width="786" alt="screenshot 103" src="https://user-images.githubusercontent.com/265597/40142922-4fa99218-595a-11e8-8b71-7e70b32a5bd9.png">

**Comment by lucianoortizsilva** [comment]
Add in your POM:

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>5.3.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

**Comment by kuniss** [comment]
This seems not to work (again?). For a freshly created Xtext project, created with the wizard, I get the following exception on a just added parsing test:
```
java.lang.NoClassDefFoundError: org/junit/platform/commons/PreconditionViolationException
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createFilteredTest(JUnit5TestLoader.java:70)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createTest(JUnit5TestLoader.java:64)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.loadTests(JUnit5TestLoader.java:53)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.PreconditionViolationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
It's not urgent at all. I will switch back to Junit4. ... I just hit the Junit5 readio button at the wizard w/o thinking a lot.

My configuration:
Eclipse 2019-12
Xtext 2.20
Gradle project dependencies:
```
testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.eclipse.xtext:xtext-dev-bom:2.20.0
|    +--- org.junit.jupiter:junit-jupiter-api:5.1.0 (c)
|    +--- org.junit.jupiter:junit-jupiter-engine:5.1.0 (c)
|    +--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.8.1 (c)
|    +--- junit:junit:4.12 (c)
|    +--- org.eclipse.platform:org.eclipse.equinox.common:3.10.500 (c)
|    +--- org.eclipse.platform:org.eclipse.core.runtime:3.16.0 (c)
|    +--- org.eclipse.jdt:org.eclipse.jdt.core:3.19.0 (c)
|    +--- org.eclipse.jdt:org.eclipse.jdt.compiler.apt:1.3.700 (c)
|    +--- org.eclipse.jdt:org.eclipse.jdt.compiler.tool:1.2.600 (c)
|    +--- log4j:log4j:1.2.17 (c)
|    +--- org.eclipse.platform:org.eclipse.osgi:3.15.0 (c)
|    +--- org.eclipse.emf:org.eclipse.emf.common:2.12.0 (c)
|    +--- org.eclipse.emf:org.eclipse.emf.ecore.xmi:2.12.0 (c)
|    +--- com.google.inject:guice:3.0 (c)
|    +--- org.antlr:antlr-runtime:3.2 (c)
|    +--- org.eclipse.emf:org.eclipse.emf.ecore.change:2.11.0 (c)
|    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.8.1 (c)
|    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.8.1 (c)
|    +--- org.eclipse.platform:org.eclipse.core.jobs:3.10.500 (c)
|    +--- org.eclipse.platform:org.eclipse.equinox.registry:3.8.500 (c)
|    +--- org.eclipse.platform:org.eclipse.equinox.preferences:3.7.500 (c)
|    +--- org.eclipse.platform:org.eclipse.core.contenttype:3.7.400 (c)
|    +--- org.eclipse.platform:org.eclipse.equinox.app:1.4.300 (c)
|    +--- org.eclipse.platform:org.eclipse.core.resources:3.13.500 (c)
|    +--- org.eclipse.platform:org.eclipse.core.filesystem:1.7.500 (c)
|    +--- org.eclipse.platform:org.eclipse.text:3.9.0 (c)
|    +--- org.eclipse.emf:org.eclipse.emf.ecore:2.12.0 (c)
|    +--- org.ow2.asm:asm-commons:7.2 (c)
|    +--- io.github.classgraph:classgraph:4.8.35 (c)
|    +--- org.eclipse.platform:org.eclipse.core.expressions:3.6.500 (c)
|    +--- org.eclipse.platform:org.eclipse.core.commands:3.9.500 (c)
|    +--- com.google.guava:guava:27.1-jre (c)
|    +--- org.ow2.asm:asm:7.2 (c)
|    +--- org.ow2.asm:asm-tree:7.2 (c)
|    +--- com.google.code.findbugs:jsr305:3.0.2 (c)
|    \--- com.google.errorprone:error_prone_annotations:2.2.0 (c)
+--- project :de.grammarcraft.epsilon
|    +--- org.eclipse.xtext:xtext-dev-bom:2.20.0 (*)
|    +--- org.eclipse.xtext:org.eclipse.xtext:2.20.0
|    |    +--- org.eclipse.xtext:org.eclipse.xtext.util:2.20.0
|    |    |    +--- org.eclipse.xtend:org.eclipse.xtend.lib:2.20.0
|    |    |    |    +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.20.0
|    |    |    |    |    \--- com.google.guava:guava:27.1-jre
|    |    |    |    |         +--- com.google.guava:failureaccess:1.0.1
|    |    |    |    |         +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    |    |    |    |         +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |    |    |         +--- org.checkerframework:checker-qual:2.5.2
|    |    |    |    |         +--- com.google.errorprone:error_prone_annotations:2.2.0
|    |    |    |    |         +--- com.google.j2objc:j2objc-annotations:1.1
|    |    |    |    |         \--- org.codehaus.mojo:animal-sniffer-annotations:1.17
|    |    |    |    \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.20.0
|    |    |    |         \--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.20.0 (*)
|    |    |    +--- log4j:log4j:1.2.17
|    |    |    +--- org.eclipse.emf:org.eclipse.emf.common:2.12.0
|    |    |    +--- org.eclipse.emf:org.eclipse.emf.ecore:2.12.0
|    |    |    \--- com.google.inject:guice:3.0
|    |    |         +--- javax.inject:javax.inject:1
|    |    |         \--- aopalliance:aopalliance:1.0
|    |    +--- org.eclipse.xtend:org.eclipse.xtend.lib:2.20.0 (*)
|    |    +--- log4j:log4j:1.2.17
|    |    +--- org.eclipse.platform:org.eclipse.equinox.common:3.10.500
|    |    +--- org.eclipse.platform:org.eclipse.osgi:3.15.0
|    |    +--- org.eclipse.emf:org.eclipse.emf.common:2.12.0
|    |    +--- org.eclipse.emf:org.eclipse.emf.ecore.xmi:2.12.0
|    |    +--- com.google.inject:guice:3.0 (*)
|    |    \--- org.antlr:antlr-runtime:3.2
|    \--- org.eclipse.xtext:org.eclipse.xtext.xbase:2.20.0
|         \--- org.eclipse.xtext:org.eclipse.xtext.common.types:2.20.0
|              +--- org.eclipse.xtext:org.eclipse.xtext:2.20.0 (*)
|              +--- org.ow2.asm:asm-commons:7.2
|              |    +--- org.ow2.asm:asm:7.2
|              |    +--- org.ow2.asm:asm-tree:7.2
|              |    |    \--- org.ow2.asm:asm:7.2
|              |    \--- org.ow2.asm:asm-analysis:7.2
|              |         \--- org.ow2.asm:asm-tree:7.2 (*)
|              \--- io.github.classgraph:classgraph:4.8.35
+--- org.junit.jupiter:junit-jupiter-api -> 5.1.0
|    +--- org.apiguardian:apiguardian-api:1.0.0
|    +--- org.opentest4j:opentest4j:1.0.0
|    \--- org.junit.platform:junit-platform-commons:1.1.0
|         \--- org.apiguardian:apiguardian-api:1.0.0
+--- org.eclipse.xtext:org.eclipse.xtext.testing:2.20.0
|    +--- org.eclipse.xtext:org.eclipse.xtext:2.20.0 (*)
|    +--- org.eclipse.xtext:org.eclipse.xtext.ide:2.20.0
|    |    +--- org.eclipse.xtext:org.eclipse.xtext:2.20.0 (*)
|    |    +--- org.eclipse.emf:org.eclipse.emf.ecore.change:2.11.0
|    |    \--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.8.1
|    |         +--- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.8.1
|    |         |    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.8.1
|    |         |    |    \--- com.google.code.gson:gson:2.8.2
|    |         |    \--- org.eclipse.xtend:org.eclipse.xtend.lib:2.18.0 -> 2.20.0 (*)
|    |         \--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.8.1 (*)
|    \--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.8.1 (*)
+--- org.eclipse.xtext:org.eclipse.xtext.xbase.testing:2.20.0
|    +--- org.eclipse.xtext:org.eclipse.xtext.xbase:2.20.0 (*)
|    +--- org.eclipse.xtext:org.eclipse.xtext.testing:2.20.0 (*)
|    +--- junit:junit:4.12
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.eclipse.platform:org.eclipse.equinox.common:3.10.500
|    +--- org.eclipse.platform:org.eclipse.core.runtime:3.16.0
|    |    +--- org.eclipse.platform:org.eclipse.osgi:[3.13.0,4.0.0) -> 3.15.0
|    |    +--- org.eclipse.platform:org.eclipse.equinox.common:[3.10.0,4.0.0) -> 3.10.500
|    |    +--- org.eclipse.platform:org.eclipse.core.jobs:[3.10.0,4.0.0) -> 3.10.500
|    |    |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.8.0,4.0.0) -> 3.10.500
|    |    +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.8.0,4.0.0) -> 3.8.500
|    |    |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.7.0,4.0.0) -> 3.10.500
|    |    +--- org.eclipse.platform:org.eclipse.equinox.preferences:[3.7.0,4.0.0) -> 3.7.500
|    |    |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.10.500
|    |    +--- org.eclipse.platform:org.eclipse.core.contenttype:[3.7.0,4.0.0) -> 3.7.400
|    |    |    +--- org.eclipse.platform:org.eclipse.equinox.preferences:[3.2.0,4.0.0) -> 3.7.500 (*)
|    |    |    +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.2.0,4.0.0) -> 3.8.500 (*)
|    |    |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.10.500
|    |    \--- org.eclipse.platform:org.eclipse.equinox.app:[1.3.0,) -> 1.4.300
|    |         +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.4.0,4.0.0) -> 3.8.500 (*)
|    |         \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.10.500
|    +--- org.eclipse.jdt:org.eclipse.jdt.core:3.19.0
|    |    +--- org.eclipse.platform:org.eclipse.core.resources:[3.12.0,4.0.0) -> 3.13.500
|    |    |    +--- org.eclipse.platform:org.eclipse.core.expressions:[3.2.0,4.0.0) -> 3.6.500
|    |    |    |    \--- org.eclipse.platform:org.eclipse.core.runtime:[3.3.0,4.0.0) -> 3.16.0 (*)
|    |    |    +--- org.eclipse.platform:org.eclipse.core.filesystem:[1.3.0,2.0.0) -> 1.7.500
|    |    |    |    +--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.10.500
|    |    |    |    +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.2.0,4.0.0) -> 3.8.500 (*)
|    |    |    |    \--- org.eclipse.platform:org.eclipse.osgi:[3.2.0,4.0.0) -> 3.15.0
|    |    |    \--- org.eclipse.platform:org.eclipse.core.runtime:[3.12.0,4.0.0) -> 3.16.0 (*)
|    |    +--- org.eclipse.platform:org.eclipse.core.runtime:[3.13.0,4.0.0) -> 3.16.0 (*)
|    |    +--- org.eclipse.platform:org.eclipse.core.filesystem:[1.7.0,2.0.0) -> 1.7.500 (*)
|    |    \--- org.eclipse.platform:org.eclipse.text:[3.6.0,4.0.0) -> 3.9.0
|    |         +--- org.eclipse.platform:org.eclipse.core.commands:[3.5.0,4.0.0) -> 3.9.500
|    |         |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.10.500
|    |         +--- org.eclipse.platform:org.eclipse.equinox.common:[3.5.0,4.0.0) -> 3.10.500
|    |         +--- org.eclipse.platform:org.eclipse.equinox.preferences:[3.7.0,4.0.0) -> 3.7.500 (*)
|    |         \--- org.eclipse.platform:org.eclipse.core.runtime:[3.14.0,4.0.0) -> 3.16.0 (*)
|    +--- org.eclipse.jdt:org.eclipse.jdt.compiler.apt:1.3.700
|    |    \--- org.eclipse.jdt:org.eclipse.jdt.core:[3.5.0,4.0.0) -> 3.19.0 (*)
|    \--- org.eclipse.jdt:org.eclipse.jdt.compiler.tool:1.2.600
|         \--- org.eclipse.jdt:org.eclipse.jdt.core:[3.3.0,4.0.0) -> 3.19.0 (*)
\--- org.junit.jupiter:junit-jupiter-engine -> 5.1.0
     +--- org.apiguardian:apiguardian-api:1.0.0
     +--- org.junit.platform:junit-platform-engine:1.1.0
     |    +--- org.apiguardian:apiguardian-api:1.0.0
     |    +--- org.junit.platform:junit-platform-commons:1.1.0 (*)
     |    \--- org.opentest4j:opentest4j:1.0.0
     \--- org.junit.jupiter:junit-jupiter-api:5.1.0 (*)
```

**Comment by cdietrich** [comment]
@ArneDeutsch is this not part of our tests or do they run on oxygen only and no junit 5?

**Comment by cdietrich** [comment]
to me this looks like that jdt does no longer work with older junit5 versions

**Comment by cdietrich** [comment]
e.g. setting

```
	testCompile 'org.junit.jupiter:junit-jupiter-api:5.5.0'
	testRuntime 'org.junit.jupiter:junit-jupiter-engine:5.5.0'
```

seems to work.
maybe we should update the junit5 version in the bom and dont care about oxygen people anymore

**Comment by cdietrich** [comment]
=> this should also be handled in a different/new issue

**Comment by miklossy** [comment]
I created a separate issue: https://github.com/eclipse/xtext-eclipse/issues/1343
