### ISSUE TITLE
The isPlatformResource guard in ParallelResourceLoader.loadResource does not work for resources in jars

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#665]
`ParallelResourceLoader.loadResource` has a guard that does not load out of sync workspace resources to avoid a deadlock between the loading thread (that would need a workspace lock to do a refresh) and the builder thread (that actually holds the workspace lock)

currently this guard simply does a check for `uri.isPlatformResource()`. but this wont match for a uri like `archive:platform:/resource/Program/extLib/SmartFlow.jar!/org/eclipse/xtext/Xtext.ecore`

so we run right into that deadlock

```
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:313)
	- locked <0x00000004c222ed50> (a java.lang.Object)
	at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:202)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:92)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:308)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:121)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2188)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1552)
	at org.eclipse.core.internal.resources.File.refreshLocal(File.java:316)
	at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl$WorkbenchHelper.createPlatformResourceInputStream(PlatformResourceURIHandlerImpl.java:205)
	at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl.createInputStream(PlatformResourceURIHandlerImpl.java:525)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:298)
	at org.eclipse.emf.ecore.resource.impl.ArchiveURIHandlerImpl$Archive.createInputStream(ArchiveURIHandlerImpl.java:118)
	at org.eclipse.emf.common.archive.ArchiveURLConnection.getInputStream(ArchiveURLConnection.java:213)
	at org.eclipse.emf.ecore.resource.impl.ArchiveURIHandlerImpl.createInputStream(ArchiveURIHandlerImpl.java:53)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:298)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1269)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25)
	- locked <0x00000006d1630f00> (a java.lang.Object)
	at org.eclipse.xtext.builder.resourceloader.AbstractResourceLoader.loadResource(AbstractResourceLoader.java:44)
	at org.eclipse.xtext.builder.resourceloader.ParallelResourceLoader.loadResource(ParallelResourceLoader.java:94)
```

I think we need an additional guard that

- check for isArchive
- looks if the `authority()` starts with `platform:/resource`
- then has a look at the archive file (use or do something similar as `org.eclipse.xtext.ui.util.ResourceUtil.getUnderlyingFile(Resource)` or find another util
- and skips loading if jar is out of sync

**Comment by cdietrich** [comment]
Fixed in 2.14
