### ISSUE TITLE
[4.9] DirtyStateEditorSupportIntegrationTest fails with latest platform builds

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#733]
```
Fehlermeldung

Document didn't change on keystroke

Stacktrace

java.lang.AssertionError: Document didn't change on keystroke
	at org.eclipse.xtext.ui.tests.editor.DirtyStateEditorSupportIntegrationTest.pushKey(DirtyStateEditorSupportIntegrationTest.java:172)
	at org.eclipse.xtext.ui.tests.editor.DirtyStateEditorSupportIntegrationTest.testSaveAndEdit(DirtyStateEditorSupportIntegrationTest.java:99)
```

**Comment by cdietrich** [comment]
needs investigation

**Comment by cdietrich** [comment]
test was problematic in the past too https://github.com/eclipse/xtext-eclipse/issues/307

**Comment by cdietrich** [comment]
i assume we need to inc. the sleep time

**Comment by cdietrich** [comment]
@iloveeclipse do you know if there were any changes regarding display.post(event)?

**Comment by cdietrich** [comment]
problem seems not to be present on mac. did not test windows yet.

**Comment by iloveeclipse** [comment]
Nope, not that I know.

**Comment by cdietrich** [comment]
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=537025
