### ISSUE TITLE
Investigate npe in test log

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#740]
```
òrg.eclipse.xtext.ui.containers.AbstractJavaProjectsState.isAffectingPackageFragmentRoots(AbstractJavaProjectsState.java:65)
	at org.eclipse.xtext.ui.containers.AbstractJavaProjectsState.isAffectingPackageFragmentRoots(AbstractJavaProjectsState.java:79)
	at org.eclipse.xtext.ui.containers.AbstractJavaProjectsState.isAffectingPackageFragmentRoots(AbstractJavaProjectsState.java:63)
	at org.eclipse.xtext.ui.containers.AbstractJavaProjectsState.elementChanged(AbstractJavaProjectsState.java:50)
	at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyListeners(DeltaProcessor.java:1723)
	at org.eclipse.jdt.internal.core.DeltaProcessor.firePostChangeDelta(DeltaProcessor.java:1556)
	at org.eclipse.jdt.internal.core.DeltaProcessor.fire(DeltaProcessor.java:1532)
	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyAndFire(DeltaProcessor.java:2253)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2143)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:474)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:297)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:287)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:150)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:376)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1499)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2302)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:128)
	at org.eclipse.xtext.ui.testing.util.IResourcesSetupUtil.createFile(IResourcesSetupUtil.java:245)
	at org.eclipse.xtext.ui.tests.scoping.namespaces.AbstractContainerRelatedTests.createFileAndRegisterResource(AbstractContainerRelatedTests.java:73)
	at org.eclipse.xtext.ui.tests.scoping.namespaces.JavaProjectsStateTest.setUp(JavaProjectsStateTest.java:40)
	at sun.re
```

**Comment by cdietrich** [comment]
Fixed in 2.15
