### ISSUE TITLE
Xtext 'Domain-Model Example' failing Runtime test cases.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#753]
When creating a fresh Xtext 'Domain-Model Example' (Xtext Complete SDK 2.15.0.v20180714-0209) into a Photon Workspace, all the XbaseIntegrationTest and all the CompilerTest are failing

![screenshot](https://user-images.githubusercontent.com/20393472/42761061-b8d98a7c-890c-11e8-9646-66840003546d.png)

with the following error message:
```
com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: org/eclipse/jdt/core/compiler/CategorizedProblem
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:950)
	at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:957)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:943)
	at org.eclipse.xtext.testing.XtextRunner.createTest(XtextRunner.java:33)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.eclipse.xtext.testing.XtextRunner.superMethodBlock(XtextRunner.java:61)
	at org.eclipse.xtext.testing.XtextRunner.methodBlock(XtextRunner.java:44)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jdt/core/compiler/CategorizedProblem
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 27 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.core.compiler.CategorizedProblem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more
```

When adding `org.eclipse.jdt.core` as Require-Bundle to the MANIFEST.MF of the `org.eclipse.xtext.example.domainmodel.tests` test plugin, the problems are gone and all runtime tests succeed.

However, I am not sure if this is the right fix for the problem. 
@cdietrich @kthoms @ArneDeutsch Could you please check these test cases on your computer and confirm whether the problem occurs on your computer as well. Thanks!

**Comment by cdietrich** [comment]
hi did you add jdt.core to the domain model examples classpath?

**Comment by miklossy** [comment]
Maybe `visibility:=reexport` is missing there
https://github.com/eclipse/xtext-extras/blob/0a60b5be229a0bacede4d12e38d31117d069dd60/org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF#L10-L11

**Comment by cdietrich** [comment]
yes i am never sure when this needs to be added and when not

**Comment by szarnekow** [comment]
It's necessary when consumers of the bundle do not use OSGi but plain Java processes. For the OSGi case, it's nice to reexport a dependency, when you do expose types of that dependency on any of your own exported classes.

**Comment by cdietrich** [comment]
Fixed via https://github.com/eclipse/xtext-extras/pull/275/commits/d22c6f16ad8305916ee7269b794f21aa9f7909e0 in 2.15

**Comment by cdietrich** [comment]
thx @miklossy
