### ISSUE TITLE
NPE in CurrentDescriptions.ResourceSetAware

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#758]
saw this today in my xtext dev ws. no idea how to reprodcue

```
java.lang.NullPointerException
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl$EAdapterList.getAdapterForType(BasicNotifierImpl.java:348)
	at org.eclipse.emf.ecore.util.EcoreUtil.getAdapter(EcoreUtil.java:152)
	at org.eclipse.xtext.builder.clustering.CurrentDescriptions$ResourceSetAware.setContext(CurrentDescriptions.java:162)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider.getResourceDescriptions(ResourceDescriptionsProvider.java:117)
	at org.eclipse.xtext.common.types.xtext.AbstractProjectAwareResourceDescriptionsProvider.getResourceDescriptions(AbstractProjectAwareResourceDescriptionsProvider.java:45)
	at org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider.getResourceDescriptions(ResourceDescriptionsProvider.java:73)
	at org.eclipse.xtext.resource.persistence.PortableURIs.getPortableURIFragment(PortableURIs.java:241)
	at org.eclipse.xtext.resource.persistence.PortableURIs.toPortableURI(PortableURIs.java:230)
	at org.eclipse.xtext.resource.persistence.PortableURIs.toPortableURI(PortableURIs.java:208)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable$1.writeURI(ResourceStorageWritable.java:98)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveEObject(BinaryResourceImpl.java:1196)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable$1.saveEObject(ResourceStorageWritable.java:111)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveFeatureValue(BinaryResourceImpl.java:1285)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveFeatureValue(BinaryResourceImpl.java:1256)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveEObject(BinaryResourceImpl.java:1229)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable$1.saveEObject(ResourceStorageWritable.java:111)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveEObjects(BinaryResourceImpl.java:1003)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveFeatureValue(BinaryResourceImpl.java:1293)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveFeatureValue(BinaryResourceImpl.java:1256)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveEObject(BinaryResourceImpl.java:1229)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable$1.saveEObject(ResourceStorageWritable.java:111)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveFeatureValue(BinaryResourceImpl.java:1270)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveFeatureValue(BinaryResourceImpl.java:1256)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveEObject(BinaryResourceImpl.java:1229)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable$1.saveEObject(ResourceStorageWritable.java:111)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveEObjects(BinaryResourceImpl.java:1003)
	at org.eclipse.emf.ecore.resource.impl.BinaryResourceImpl$EObjectOutputStream.saveResource(BinaryResourceImpl.java:991)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable.writeContents(ResourceStorageWritable.java:116)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable.writeEntries(ResourceStorageWritable.java:66)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageWritable.writeEntries(BatchLinkableResourceStorageWritable.java:55)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable.writeResource(ResourceStorageWritable.java:51)
	at org.eclipse.xtext.resource.persistence.ResourceStorageFacade.saveResource(ResourceStorageFacade.java:125)
	at org.eclipse.xtext.builder.BuilderParticipant.saveResourceStorage(BuilderParticipant.java:681)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.handleChangedContents(ParallelBuilderParticipant.java:181)
```

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=442569 too

**Comment by cdietrich** [comment]
the code in ecoreutil has changed recently in emf (https://github.com/eclipse/emf/commit/5d88780e588170da388c2d574dcfe758bd93c101)

i wonder what caused this to happen multiple times in my mac xtext dev workspace.
still seems to be a race.

@szarnekow any idea?

@merks do you have any idea what could cause this to happen more often now?

**Comment by cdietrich** [comment]
am getting this all the time. even after restart. have a very recent emf in my dev eclipse. will try to remote debug.

**Comment by szarnekow** [comment]
It could be more likely now to produce a race now since the getAdapter directly accesses the internal field now to save a few CPU cycles. Could be that we need to put an adapter into the array that has an atomic reference / readwrite lock protected field with the real contents that's supposed to be adapted there.

**Comment by merks** [comment]
No idea why it would happen more often, but it represents a corruption of the adapters list that can really only result from multi-threaded adding of adapters, as mentioned in https://bugs.eclipse.org/bugs/show_bug.cgi?id=442569#c2 already.

The recent change is a small performance optimization to make adapter lookup "twice" as fast, so perhaps that quickness makes it more likely that multiple threads end up actually adding adapters.

**Comment by cdietrich** [comment]
the problem happens with pure read operations :(

```
public class Main {

	static class MyAdapter extends AdapterImpl {
		
	}
	
	public static void main(String[] args) {
		ResourceSetImpl rs = new ResourceSetImpl();
		rs.eAdapters().add(new MyAdapter());
		for (int k=0; k < 10; k++) {
			new Thread(new MyRunnable(rs)).start();
		}
	}
	
	static class MyRunnable implements Runnable {
		
		private ResourceSet rs;

		public MyRunnable(ResourceSet rs) {
			this.rs = rs;
		}

		@Override
		public void run() {
			while (true) {
				EcoreUtil.getAdapter(rs.eAdapters(), MyAdapter.class);
			}
			
		}
		
	}

}
```

**Comment by cdietrich** [comment]
the problem is that data has the correct size before the content is copied over

```
@Override
    public Object [] data()
    {
      safe = true;
      if (data != null && data.length != size)
      {
        if (size == 0)
        {
          data = null;
        }
        else
        {
          Object [] oldData = data;
          data = newData(size);
          System.arraycopy(oldData, 0, data, 0, size);
        }
      }
      return data;
    }
```

**Comment by cdietrich** [comment]
i wonder if emf should do something like the following. cc @merks 

```
@Override
    public Object [] data()
    {
      safe = true;
      if (data != null && data.length != size)
      {
        if (size == 0)
        {
          data = null;
        }
        else
        {
          Object [] oldData = data;
          Object [] newData = newData(size);
          System.arraycopy(oldData, 0, newData, 0, size);
          data = newData;
        }
      }
      return data;
    }
```

**Comment by cdietrich** [comment]
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=537279
