### ISSUE TITLE
Wizard error without PDE

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#870]
from https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/problems/5bc8c3d3e4b0ac09b977b327

```
Bundle: org.eclipse.ui 3.110.0.v20180828-1350
Message: Unhandled event loop exception
Exception:
java.lang.NoClassDefFoundError: org/eclipse/pde/core/plugin/PluginRegistry
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.isJUnit5PluginAvailable(AdvancedNewProjectPage.java:672)
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.lambda$12(AdvancedNewProjectPage.java:151)
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.lambda$37(AdvancedNewProjectPage.java:569)
    at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.Radio(AdvancedNewProjectPage.java:571)
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.lambda$8(AdvancedNewProjectPage.java:155)
    at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.lambda$1(AdvancedNewProjectPage.java:164)
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.lambda$35(AdvancedNewProjectPage.java:547)
    at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.Group(AdvancedNewProjectPage.java:549)
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.lambda$0(AdvancedNewProjectPage.java:166)
    at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
    at org.eclipse.xtext.xtext.ui.wizard.project.AdvancedNewProjectPage.createControl(AdvancedNewProjectPage.java:212)
    at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:179)
    at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:685)
    at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1125)
    at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1178)
    at org.eclipse.jface.wizard.WizardDialog.lambda$3(WizardDialog.java:1166)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
    at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1166)
    at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:861)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:410)
    at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
    at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
```

**Comment by cdietrich** [comment]
Fixed
