### ISSUE TITLE
NullPointer in JavaProjectFactory#enhanceProject

### ISSUE THREAD

**Issue by philgold** [eclipse/xtext-eclipse#902]
The variable folders in the superclass ProjectFactory can be null. 

`for (final String folderName : folders)`
```

Caused by: java.lang.NullPointerException
	at org.eclipse.xtext.ui.util.JavaProjectFactory.enhanceProject(JavaProjectFactory.java:60)
	at org.eclipse.xtext.ui.util.PluginProjectFactory.enhanceProject(PluginProjectFactory.java:96)
	at org.eclipse.xtext.ui.util.ProjectFactory.createProject(ProjectFactory.java:211)
```

**Comment by kthoms** [comment]
Fixed in 2.16
