### ISSUE TITLE
Codemining on Domainmodel Example throws BasicIndexOutOfBoundsException

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-eclipse#965]
When opening an empty model.dmodel file,
![screencast](https://user-images.githubusercontent.com/20393472/52212576-23f0e380-288d-11e9-9567-5ee2f87d5570.gif)
the following BasicIndexOutOfBoundsException is thrown:
```
java.util.concurrent.CompletionException: org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=0, size=0
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=0, size=0
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
	at org.eclipse.xtext.example.domainmodel.ui.codemining.DomainmodelCodeMiningProvider.createCodeMinings(DomainmodelCodeMiningProvider.java:42)
	at org.eclipse.xtext.ui.codemining.AbstractXtextCodeMiningProvider.createCodeMinings(AbstractXtextCodeMiningProvider.java:108)
	at org.eclipse.xtext.ui.codemining.AbstractXtextCodeMiningProvider$2.exec(AbstractXtextCodeMiningProvider.java:76)
	at org.eclipse.xtext.ui.codemining.AbstractXtextCodeMiningProvider$2.exec(AbstractXtextCodeMiningProvider.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:499)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:138)
	at org.eclipse.xtext.ui.codemining.AbstractXtextCodeMiningProvider.lambda$0(AbstractXtextCodeMiningProvider.java:80)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 5 more
```

It seems that the [DomainmodelCodeMiningProvider](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/codemining/DomainmodelCodeMiningProvider.java#L42) is not aware of opening an empty resource.

**Comment by cdietrich** [comment]
Fixed in 2.17
