### ISSUE TITLE
NullPointerException in JdtQueuedBuildDat#doNeedRebuild

### ISSUE THREAD

**Issue by OLibutzki** [eclipse/xtext-eclipse#988]
Hi everyone,

I use Xtext 2.13.0.

On one developer machine the following NPE occurs every time the incremental build is triggered. This leads to the effect that the XtextBuilder is reinvoked with the "full build" flag.

```
java.lang.NullPointerException
	at org.eclipse.xtext.builder.impl.javasupport.JdtQueuedBuildData.doNeedRebuild(JdtQueuedBuildData.java:116)
	at org.eclipse.xtext.builder.impl.javasupport.JdtQueuedBuildData.needsRebuild(JdtQueuedBuildData.java:104)
	at org.eclipse.xtext.builder.impl.QueuedBuildData.needRebuild(QueuedBuildData.java:250)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:240)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by ArneDeutsch** [comment]
I've inspected the code and come to the conclusion, that this particular NPE is not possible (at least for recent Xtext, but code is unlikely to have changed there) ... EXCEPT (perhaps) if multiple threads build in parallel. Probably it is a race produced by multiple builds running at the same time. Is the developer using a recent Eclipse? Probably he has configured to use more than one build thread?

Please check the preferences (see screenshot).
![screen](https://user-images.githubusercontent.com/30502733/53245609-75cba300-36ae-11e9-87d8-1f049c3a440d.png)

**Comment by OLibutzki** [comment]
Thanks for investigating. We use Eclipse Oxygen (4.7.3.v20180330-0640) and the "Max simultaneous project build" field is missing there.

**Comment by ArneDeutsch** [comment]
There is only one build thread in Oxygen. Hence no room for a multithreading issue ... strange ... then I must have missed a null possibility ...

**Comment by ArneDeutsch** [comment]
Do you have closed projects in the workspace that are not located directly in the workspace (external projects)?

**Comment by OLibutzki** [comment]
No

**Comment by ArneDeutsch** [comment]
I have to give up. Without the chance to debug the issue I can not pinpoint it.

The (generated) line in question is inside `JdtQueuedBuildData`

`if (((unconfirmed.getBuildNumber() < (it.getBuildNumber()).intValue()) && unconfirmed.getProject().equals(it.getProject()))) {`

I've checked `unconfirmed` `it`, `it.getBuildNumber()` and `unconfirmed.getProject()`. I can spot no possibility at all that anything of that could become `null` here. The only method that is not guarded for multiple threads seem to be `reset` (others are guarded in `QueuedBuildData`). But even if multiple threads would be existent I could not explain the NPE with that.

Provided that you do not have user code that modifies the build process somehow and sets the fields in question I'm unable to explain the issue.

**Comment by OLibutzki** [comment]
Hmm, my IDE links to line 75 in the Xtend file.

`if (oldState === null || oldState.lastStructuralBuildTime != newState.lastStructuralBuildTime) {`

**Comment by szarnekow** [comment]
Can you try this with a more recent version?

**Comment by OLibutzki** [comment]
> Can you try this with a more recent version?

I will do so when 2.17 is released. Expect my feedback ;-)

**Comment by OLibutzki** [comment]
A first smoke test with 2.17 was successful -> the NPE did not occur anymore.

**Comment by szarnekow** [comment]
Thank you for coming back to this
